var N = null;var sourcesIndex = {};
sourcesIndex["linfa"] = {"name":"","dirs":[{"name":"composing","files":["mod.rs","multi_class_model.rs","multi_target_model.rs","platt_scaling.rs"]},{"name":"dataset","files":["impl_dataset.rs","impl_records.rs","impl_targets.rs","iter.rs","lapack_bounds.rs","mod.rs"]}],"files":["correlation.rs","error.rs","lib.rs","metrics_classification.rs","metrics_clustering.rs","metrics_regression.rs","param_guard.rs","prelude.rs","traits.rs"]};
sourcesIndex["linfa_bayes"] = {"name":"","files":["base_nb.rs","error.rs","gaussian_nb.rs","hyperparams.rs","lib.rs","multinomial_nb.rs"]};
sourcesIndex["linfa_clustering"] = {"name":"","dirs":[{"name":"appx_dbscan","dirs":[{"name":"cells_grid","files":["cell.rs","mod.rs"]},{"name":"clustering","files":["mod.rs"]},{"name":"counting_tree","files":["mod.rs"]}],"files":["algorithm.rs","hyperparams.rs","mod.rs"]},{"name":"dbscan","files":["algorithm.rs","hyperparams.rs","mod.rs"]},{"name":"gaussian_mixture","files":["algorithm.rs","errors.rs","hyperparams.rs","mod.rs"]},{"name":"k_means","files":["algorithm.rs","errors.rs","hyperparams.rs","init.rs","mod.rs"]},{"name":"optics","files":["algorithm.rs","errors.rs","hyperparams.rs","mod.rs"]}],"files":["lib.rs"]};
sourcesIndex["linfa_datasets"] = {"name":"","files":["generate.rs","lib.rs"]};
sourcesIndex["linfa_elasticnet"] = {"name":"","files":["algorithm.rs","error.rs","hyperparams.rs","lib.rs"]};
sourcesIndex["linfa_ftrl"] = {"name":"","files":["algorithm.rs","error.rs","hyperparams.rs","lib.rs"]};
sourcesIndex["linfa_hierarchical"] = {"name":"","files":["error.rs","lib.rs"]};
sourcesIndex["linfa_ica"] = {"name":"","files":["error.rs","fast_ica.rs","hyperparams.rs","lib.rs"]};
sourcesIndex["linfa_kernel"] = {"name":"","files":["inner.rs","lib.rs","sparse.rs"]};
sourcesIndex["linfa_linear"] = {"name":"","dirs":[{"name":"glm","files":["distribution.rs","hyperparams.rs","link.rs","mod.rs"]}],"files":["error.rs","float.rs","lib.rs","ols.rs"]};
sourcesIndex["linfa_logistic"] = {"name":"","files":["argmin_param.rs","error.rs","float.rs","hyperparams.rs","lib.rs"]};
sourcesIndex["linfa_nn"] = {"name":"","files":["balltree.rs","distance.rs","heap_elem.rs","kdtree.rs","lib.rs","linear.rs"]};
sourcesIndex["linfa_pls"] = {"name":"","files":["errors.rs","hyperparams.rs","lib.rs","pls_generic.rs","pls_svd.rs","utils.rs"]};
sourcesIndex["linfa_preprocessing"] = {"name":"","dirs":[{"name":"countgrams","files":["hyperparams.rs","mod.rs"]}],"files":["error.rs","helpers.rs","lib.rs","linear_scaling.rs","norm_scaling.rs","tf_idf_vectorization.rs","whitening.rs"]};
sourcesIndex["linfa_reduction"] = {"name":"","dirs":[{"name":"diffusion_map","files":["algorithms.rs","hyperparams.rs","mod.rs"]}],"files":["error.rs","lib.rs","pca.rs","utils.rs"]};
sourcesIndex["linfa_svm"] = {"name":"","files":["classification.rs","error.rs","hyperparams.rs","lib.rs","permutable_kernel.rs","regression.rs","solver_smo.rs"]};
sourcesIndex["linfa_trees"] = {"name":"","dirs":[{"name":"decision_trees","files":["algorithm.rs","hyperparams.rs","iter.rs","mod.rs","tikz.rs"]}],"files":["lib.rs"]};
sourcesIndex["linfa_tsne"] = {"name":"","files":["error.rs","hyperparams.rs","lib.rs"]};
createSourceSidebar();
